#!/bin/sh
mongo-connector -m localhost:27017 \
-t http://localhost:8983/solr/content_items \
-d solr_doc_manager \
-n eumssi_db.content_items \
--auto-commit-interval=30 \
--oplog-ts content_items.timestamp
